### ISSUE TITLE
Feature Changes- Metrics to be added

### ISSUE THREAD

**Issue by siddharthjain1611** [CovidToday/backend#34]
Following metrics need to be calculated from source data, and printed onto output json and csv. 
(code to be added in PosRateNew.ipynb)

- [ ] daily cases per million

- [ ] daily tests per million

- [ ] daily tests moving avg (7 day)

- [ ] daily deaths moving avg (7 day)

Rationale:
daily cases per million: also called incidence per million tells us the rate of epidemic growth for that states size and population. 
daily tests per million: is more important rather than the currently used cumulative tests per million, since cumulative TPM will always increase and is thus limited in utility. 
daily tests moving avg (7 day) and daily deaths moving avg (7 day): moving avgs smooth out the weekly fluctuations which are artifacts due to the reporting system.

**Comment by msudhanshu10** [comment]
I will be contributing in this issue.

**Comment by msudhanshu10** [comment]
I can see a lot of csv files in testing-and-cfr directory. Can you give me clarity on the source data files?

**Comment by MGMD-96** [comment]
The python script fetches the source json through wget and puts it in the directory as test.json

Output files are multiple. The consolidated outputs are covidtoday.json and com.csv

Once we complete the development, we will change these names and clean the repo.
